#!/usr/bin/env perl

use strict;
use warnings;

use v5.14;

my @tags = qw(2020.01 2020.02 2020.05.1 2020.06 2020.07 2020.08.2 2020.09 2020.10 2020.11 2020.12 2021.02 2021.02.1 2021.03 2021.04 2021.05 2021.06 2021.07 2021.08 2021.09 2021.10);

my $image_name = "raku";

for my $release ( @tags ) {
  my @build_tags = ($release, "gha-$release");
  for my $my_tag ( @build_tags ) {
    my $image = "jjmerelo/$image_name:$my_tag";
    my $uid = $tag =~ /gha/ ? 1001: 1000;
    say "👷 Building $image";
    `docker build . -f Dockerfile --build-arg RAKU_RELEASE=$release --build-arg UID=$uid -t $image`;
    `docker push $image`;
    if ( $tag eq $tags[-1] ) {
      `docker tag $image  jjmerelo/$image_name:latest`;
      `docker push jjmerelo/$image_name:latest`;
    }
  }
}
