name: Test-create and publish a Docker image

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/upload-ghcr.yaml

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push to GHCR container image
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: ${{ env.REGISTRY }}/jj/raku

      - name: Build and push to GHCR GHA-specific image
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          build-args: |
            UID=1001
            USER_HOME=/github/home
          tags: ${{ env.REGISTRY }}/jj/raku-gha


