name: Test-create and publish a Docker image to Docker hub

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/upload-dockerhub.yaml
    schedule:
      - cron: "0 1 1 * *"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Log in to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Get release in Dockerfile
        id: dockerfile-version
        run: echo DOCKERFILE_VERSION=$(.github/workflows/get_release.pl)>> "$GITHUB_OUTPUT"
      - name: Build and push to Docker Hub container image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: jjmerelo/raku:latest, jjmerelo/raku:${{ steps.dockerfile-version.outputs.DOCKERFILE_VERSION }}


