name: Deploy weekly to Docker hub

on:
  push:
  schedule:
      - cron: "2 0 * * FRI"

jobs:
  build-weekly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Get date tag
        id: date_tag
        run: |
          OUTPUT='::set-output name=DATE_TAG::'
          OUTPUT+=$(date +"%Y%m%d")
          echo -n $OUTPUT
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: jjmerelo/raku:weekly.${{ steps.date_tag.outputs.DATE_TAG }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
